server:
  http2:
    enabled: true
spring:
  application:
    name: source-downloader
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
  datasource:
    username: sd
    password: sd
    url: jdbc:sqlite:${source-downloader.data-location}source-downloader.db
    driver-class-name: org.sqlite.JDBC
  flyway:
    locations:
      - classpath:/db/migration
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  exposed:
    generate-ddl: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.JdbcTemplateAutoConfiguration
  jackson:
    default-property-inclusion: non_null
  threads:
    virtual:
      enabled: true
  output:
    ansi:
      enabled: always
source-downloader:
  data-location: ${SOURCE_DOWNLOADER_DATA_LOCATION:./}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
    env:
      show-values: ALWAYS
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(%5p) %clr(${PID:- }){magenta} %clr([%15.15t]){cyan} %-40.40logger{39} %clr(:){cyan} %m%n%wex"
---
spring:
  config:
    activate:
      on-profile:
        - debug
        - development
        - dev
  exposed:
    show-sql: true
logging:
  level:
    telegram4j: debug
    reactor: debug
    io.github.shoaky: trace
    org.springframework.web: debug
    Exposed: debug
management:
  endpoint:
    configprops:
      show-values: always
    env:
      show-values: always
  endpoints:
    web:
      cors:
        allowed-origins: "*"

---
spring:
  config:
    activate:
      on-profile:
        - integration-test
  datasource:
    url: "jdbc:sqlite::memory:"
  exposed:
    show-sql: true
source-downloader:
  data-location: src/test/resources

logging:
  level:
    Exposed: debug
    SourceProcessor: debug
---
spring:
  config:
    activate:
      on-profile:
        - production
        - debug
logging:
  file:
    name: ${source-downloader.data-location}logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-history: 7
      max-file-size: 100MB
---
spring:
  config:
    activate:
      on-profile:
        - production
logging:
  level:
    telegram4j.mtproto.MTProtoClient: warn