CREATE TABLE TARGET_PATH_RECORD
(
    ID          CHARACTER VARYING PRIMARY KEY,
    CREATE_TIME DATETIME
);

CREATE TABLE PROCESSING_RECORD
(
    ID                  BIGINT PRIMARY KEY,
    PROCESSOR_NAME      VARCHAR(255) NOT NULL,
    SOURCE_ITEM_HASHING VARCHAR(64)  NOT NULL,
    SOURCE_CONTENT      JSON,
    RENAME_TIMES        INT      DEFAULT 0,
    STATUS              INT      DEFAULT 0,
    MODIFY_TIME         DATETIME DEFAULT NULL,
    CREATE_TIME         DATETIME
);
CREATE UNIQUE INDEX UIDX_PROCESSORNAME_SOURCEITEMHASHING ON PROCESSING_RECORD (PROCESSOR_NAME, SOURCE_ITEM_HASHING);
CREATE SEQUENCE processing_record_seq START WITH 1 INCREMENT BY 50;
