spring:
  application:
    name: source-downloader
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
  datasource:
    username: sd
    password: sd
    url: jdbc:sqlite:${source-downloader.data-location}source-downloader.db
    driver-class-name: org.sqlite.JDBC
  flyway:
    locations:
      - classpath:/db/migration
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  exposed:
    generate-ddl: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.JdbcTemplateAutoConfiguration
  jackson:
    default-property-inclusion: non_null
source-downloader:
  data-location: ${SOURCE_DOWNLOADER_DATA_LOCATION:./}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
---
spring:
  config:
    activate:
      on-profile:
        - debug
        - development
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
  exposed:
    show-sql: true
logging:
  level:
    telegram4j: debug
    reactor: debug
    io.github.shoaky: trace
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.web: debug

---
spring:
  config:
    activate:
      on-profile:
        - integration-test
  datasource:
    url: "jdbc:sqlite::memory:"
  exposed:
    show-sql: true
source-downloader:
  data-location: src/test/resources

springdoc:
  api-docs:
    enabled: false
---
spring:
  config:
    activate:
      on-profile:
        - production
        - debug
logging:
  file:
    name: ${source-downloader.data-location}logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-history: 7
      max-file-size: 100MB