trigger:
  - name: 30min
    type: fixed
    props:
      interval: PT30M
  - name: 1hour
    type: fixed
    props:
      interval: PT1H
  - name: 1day
    type: fixed
    props:
      interval: P1D
  - name: webhook
    type: webhook
    props:
      path: default