package io.github.shoaky.sourcedownloader.sdk.component

@Suppress("PropertyName")
data class JsonSchema(
    val `$schema`: String? = null,
    val `$id`: String? = null,
    val `$ref`: String? = null,
    val `$comment`: String? = null,
    val title: String? = null,
    val description: String? = null,
    val type: String? = null,
    val properties: Map<String, JsonSchema>? = null,
    val required: List<String>? = null,
    val enum: List<Any>? = null,
    val const: Any? = null,
    val default: Any? = null,
    val examples: List<Any>? = null,
    val multipleOf: Double? = null,
    val maximum: Double? = null,
    val exclusiveMaximum: Double? = null,
    val minimum: Double? = null,
    val exclusiveMinimum: Double? = null,
    val maxLength: Int? = null,
    val minLength: Int? = null,
    val pattern: String? = null,
    val additionalProperties: Any? = null,
    val items: Any? = null,
    val contains: JsonSchema? = null,
    val maxItems: Int? = null,
    val minItems: Int? = null,
    val uniqueItems: Boolean? = null,
    val maxProperties: Int? = null,
    val minProperties: Int? = null,
    val patternProperties: Map<String, JsonSchema>? = null,
    val dependencies: Map<String, Any>? = null,
    val propertyNames: JsonSchema? = null,
    val ifCondition: JsonSchema? = null,
    val thenCondition: JsonSchema? = null,
    val elseCondition: JsonSchema? = null,
    val allOf: List<JsonSchema>? = null,
    val anyOf: List<JsonSchema>? = null,
    val oneOf: List<JsonSchema>? = null,
    val not: JsonSchema? = null,
    val format: String? = null,
    val contentEncoding: String? = null,
    val contentMediaType: String? = null,
    val `$defs`: Map<String, JsonSchema>? = null
)