name: Publish SDK
on:
  workflow_dispatch:
    inputs:
      manual_trigger:
        description: 'Manual trigger'
        required: false
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'gradle'
      - name: Build with Gradle
        run: ./gradlew sdk:build --no-daemon
      - name: Publish artifacts
        run: ./gradlew -PsonatypeUsername=${{ secrets.SONATYPE_USERNAME }} -PsonatypePassword=${{ secrets.SONATYPE_PASSWORD }} -PsigningKey="${{ secrets.SIGNING_KEY }}" -PsigningPassword=${{ secrets.SIGNING_PASSWORD }} sdk:publish --no-daemon